apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: simple-app
  name: simple-app
  namespace: ronaldinho
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-app
  template:
    metadata:
      labels:
        app: simple-app
    spec:
      containers:
      - image: tawliew/node-ronaldinho:v1.0.0 
        name: nginx
        env:
          - name: NODEPORT
            valueFrom:
              secretKeyRef:
                name: simple-app-secret
                key: nodeport
