apiVersion: v1
kind: Service
metadata:
  name: simple-app-service
  namespace: ronaldinho
spec:
  type: NodePort
  selector:
    app: simple-app 
  ports:
    - port: 80
      targetPort: 80
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30101

